name: ALEMCExchange
version: 1.1.1
author: Allen_Linong
main: com.alemcexchange.ALEMCExchangePlugin
api-version: 1.20

commands:
  alemcexchange:
    description: Main command for ALEMCExchange
    usage: /<command> [help|sell|exchange|browse|balance|autosell|pay|reload|give|unlockall]
    aliases:
      - alex
      - aex

permissions:
  alemcexchange.use:
    description: Allow using basic commands
    default: true
  alemcexchange.admin:
    description: Allow using admin commands
    default: op
    children:
      alemcexchange.use: true
      alemcexchange.autosell: true
      alemcexchange.notax: true
      alemcexchange.vip: true
      alemcexchange.premium: true
      alemcexchange.unlockall.auto: true
  alemcexchange.autosell:
    description: Allow using auto sell feature
    default: false
  alemcexchange.notax:
    description: No tax when selling
    default: false
  alemcexchange.vip:
    description: VIP status with 3% tax
    default: false
  alemcexchange.premium:
    description: Premium status with 1% tax
    default: false
  alemcexchange.unlockall.auto:
    description: Auto unlock all items
    default: false
